url: https://amazingworks.github.io
baseurl: ""

# Site settings
title: AmazingWorks
email: conatos@amazingworks.com..br
description: "Performance e SEO"


# Team names, titles and social links
people:
- name: Ezequiel Bertti
  pic: ebertti
  position: Arquiteto de Sistemas
  social:
    - title: twitter
      url: https://twitter.com/ebertti
    - title: github
      url: https://github.com/ebertti
    - title: stack-overflow
      url: https://stackoverflow.com/users/192684/ezequiel-bertti

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Av Afonso Arino de Melo Branco
  - line: Barra da Tijuca, Rio de Janeiro

# Build settings
markdown: kramdown
permalink: pretty